<a href="https://www.kaggle.com/code/ayushs9020/re-creating-gaussian-naive-bayes?scriptVersionId=136380286" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Gaussian Naive Bayes


Gaussian Naive Bayes (GNB) is a classification algorithm based on the Bayes theorem and the assumption that the features are independent and identically distributed (i.i.d.) Gaussian variables. This means that each feature is assumed to be normally distributed, and that the distribution of each feature is the same for all classes.

# 1 | Basic Terminologies 🧿

* $Probablity$
* $Condtional$ $Probablity$
* $Chain$ $Rule$ $In$ $Condtional$ $Probablity$
* $Maximum$ a $Postirier$

In [1]:
from IPython.display import IFrame

## 1.1 | Probablity 

So what is this term `probablity`

Probability is the measure of the likelihood of an event occurring, given some observations of the past. 

The Probablity $p(x)$ of an event $x$ occuring in $n$ number of events is given by
$$p(x) = \frac {x}{n}$$
For example the probablity of `Heads` occuring when a `coin` is tossed is $50$%. Here we have considered only two outcomes `Heads` and `Tails`.

So now we have a basic idea of the term proablity 

Now we move on to `Conditional Probablity`. So what is conditional probablity???

Conditional probability is the probability of an event occurring given that another event has already occurred. 

The conditional probablity $p(x|y)$ of an event $x$ occuring knwon that $y$ has been occured can be caluclated when given the probablity $p(x)$ of event $x$ occuring gloablly, probablity $p(y)$ of event $y$ occuring globally and the condtional probablity$p(y|x)$ or 
$$p(x|y) = p(\frac {x}{y}) = \frac {p(x)p(y|x)}{p(y)} = \frac {p(x , y)}{p(y)}$$

Saying in context to a machine Learning Algorithm, the formula changes a bit, dont worry, you will understand it. 

I have truncated $target$ to $t$ and $features$ to $f$

The conditional probablity $p(target|f_1 , f_2 , f_3 , ... , f_n)$ of an event $target$ occuring knwon that $(f_1 , f_2 , f_3 , ... , f_n)$ have been occured can be calucalted when given the probablity$p(target)$ of the event $target$ occuring gloablly, probablity $p(f_1 , f_2 , f_3 , ... , f_n)$ of events $(f_1 , f_2 , f_3 , ... , f_n)$ occuring globally and the condtional probablity $p(f_1 , f_2 , f_3 , ... , f_n|target)$ or 
 
$$p(t|f_1 , f_2 , f_3 , ... , f_n) = p(\frac {t}{f_1 , f_2 , f_3 , ... , f_n}) = \frac {p(t)p(f_1 , f_2 , f_3 , ... , f_n|t)}{p(f_1 , f_2 , f_3 , ... , f_n)} = \frac {p(t , f_1 , f_2 , f_3 , ... , f_n)}{p(f_1 , f_2 , f_3 , ... , f_n)}$$

Lets say we have $3$ events now. The contional prbablity will now be 

$$p(x|y , z) = \frac p{x}{y , z} = \frac {p(x)p(y , z|x)}{p(y , z)} = \frac {p(x , y , z)}{p(y , z)}$$

According to the cahin rule, the formula becomes like this 

$$p(x , y , z) = p(x|y , z)p(y , z)$$

([Short chain rule expalanation](https://youtu.be/WqqpwDVeW10))

Doing the same for the example 

$$p(t , f_1 , f_2 , f_3 , ... , f_n) = p(t|f_1 , f_2 , f_3 , ... , f_n)p(f_1 , f_2 , f_3 , ... , f_n)$$

We can apply the chain rule to $p(f_1 , f_2 , f_3 , ... , f_n)$ also, doing this iteratively, maybe one day we reach $p(f_n)$. But for one as of one more iteration our formula becomes 

$$= p(t|f_1 , f_2 , f_3 , ... , f_n)p(f_1 | f_2 , f_3 , ... f_n)p(f_2 , f_3 , ... , f_n)$$

We can rewrite this as 

$$= p(t|f_1 , f_2 , f_3 , ... , f_n)p(f_1 | f_2 , f_3 , ... f_n)p(f_2 , f_3 , ... , f_n) = p(t|f_1 , f_2 , f_3 , ... , f_n)p(f_1 | f_2 , f_3 , ... f_n) ... p(f_{n-1}|f_n)$$ or 

$$p(t|f_1 , f_2 , f_3 , ... , f_n) ∝ p(t)∏_{i = 1}^{n}p(f_i|t)$$

Replaing the $∝$ with $\frac {1}{z}$ we get

$$p(t|f_1 , f_2 , f_3 , ... , f_n) = \frac {1}{z} p(t)∏_{i = 1}^{n}p(f_i|t)$$

Applying the Maximum A Postirier we get. 
$$p(t|f_1 , f_2 , f_3 , ... , f_n) = argmax \frac {1}{z} p(t)∏_{i = 1}^{n}p(f_i|t)$$
([Maximum A Postiter Explanantion](https://youtu.be/tr1jxgKbNuw) enjoy the music)

## 1.2 | Probablity Desnsity Function 

We know that the curve for $x = y$ seems to be like this 

In [2]:
IFrame("https://www.desmos.com/calculator/512wkwdbob" , 1000 , 400)

If we tweeke the function a little bit like $y = e^x$, we get 

In [3]:
IFrame("https://www.desmos.com/calculator/7x5pbdhrrn" , 1000 , 400)

After tweeking the function more to $y = e^{-x}$ it becomes

In [4]:
IFrame("https://www.desmos.com/calculator/jtzzdklnrd" , 1000 , 400)

If we make a modulus function here $y = e^{-|x|}$, it becomes

In [5]:
IFrame("https://www.desmos.com/calculator/zodxwedpjj" , 1000 , 400)

An interesting fact is that, the functuon doesent really rely on $e$, it can be any constant number (except $1$, $-1$ and $0$) and it will show the same results. 

So if it doesnt change at all, we do we even put the $e$ there, why dont we just put anything else there 

Frankly speaking $e$ seems to be cool there

Also if we square the function as $y = e^{x^2}$, we get this 

In [6]:
IFrame("https://www.desmos.com/calculator/dqd1vrha9i" , 1000 , 400)

Also we can move this function in the $x$ axis by `adding/subtracting` some constant from $x$ like $y = e^{-|x - a|^2}$

In [7]:
IFrame("https://www.desmos.com/calculator/0omydtyxdh" , 1000 , 400)

What if I want to calaculate the area under of this curve ??

In [8]:
IFrame("https://www.desmos.com/calculator/1xlnxhm7zj" , 1000 , 400)

Suprisingly this area is always seems to be $\sqrt\pi$

As we know the total probabalites of all the events happening will be $1$, 

Now for making the probablity $y$ to be $1$, we need to divide the function $e^{-|x - a|^2}$ by $\sqrt {π}$, to make it $1$.

So now our formula becomes 
$$y = \frac {1}{\sqrt{\pi}}e^{-|x - a|^2}$$

Going back some steps, I would like to add one thing to this formula $y = e^{-|x^2|}$ and adding just a variable term to control this function we can rewrite this as $y = e^{-c|x^2|}$

Now if we put $c = 10$, we get this

In [9]:
IFrame("https://www.desmos.com/calculator/c5q3nl2t1g" , 1000 , 400)

After experiments it was found that $c = \frac {1}{2}$ is a great tuned parameter for the function to be more smooth and convineint for solutions 

So changing our formula a little bit we can rewrite it as $y = e^{-\frac {1}{2}|x^2|}$
Q
As we changed our $e^{-\frac {1}{2}|x^2|}$, this would aso affect the area under the curve a little bit, now we also need to divide it by $\frac {1}{2}$. Tweeking this change into the formula we get $$y = \frac {1}{\sqrt{2\pi}}e^{-\frac {1}{2}|x - a|^2}$$

After extensive research we found that, for finding the best bell like curve, we need to change the values of $a$ and $b$. Suprisingly, the value seemed out to be 
$a = mean$ or $a = μ$ and $b = standard_-deviation^2$ or $b = σ^2$. Now our formula becomes like $$y = \frac {1}{\sigma\sqrt{2\pi}}e^{-\frac {1}{2}\frac {|x - μ|^2}{\sigma^2}}$$

If you notice we are taking the square of a mode functon, What we can rather do is $$y = \frac {1}{\sigma \sqrt{2π}}e^{\frac {-(x - μ)^2}{2σ^2}}$$

And this my friends is the `Normal Distribution Fucntion`

$$F(x) = \frac {1}{\sigma \sqrt{2π}}e^{\frac {-(x - μ)^2}{2σ^2}}$$

# 2 | Making from Scratch 🌌

So how do we code this thing 

In [10]:
import pandas as pd 
import numpy as np 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/playground-series-s3e19/sample_submission.csv
/kaggle/input/playground-series-s3e19/train.csv
/kaggle/input/playground-series-s3e19/test.csv


Lets assume we have columns like this 

In [11]:
data = pd.read_csv("/kaggle/input/playground-series-s3e19/train.csv")

features = np.array([x for x in pd.DatetimeIndex(pd.to_datetime(data["date"])).month])

target = data["num_sold"]

data = pd.DataFrame([0 for _ in range(data.shape[0])])

data["feature"] = target
data["target"] = features

data

0  feature  target
0       0       63       1
1       0       66       1
2       0        9       1
3       0       59       1
4       0       49       1
...    ..      ...     ...
136945  0      700      12
136946  0      752      12
136947  0      111      12
136948  0      641      12
136949  0      539      12

[136950 rows x 3 columns]

Lets assume we try to predict `target` , with the help of `features`

Lets only focus on the value $1$ for now 

In [12]:
sample_data = data[data["target"] == 1]

sample_data , sample_data["feature"] , type(sample_data["feature"])

(        0  feature  target
 0       0       63       1
 1       0       66       1
 2       0        9       1
 3       0       59       1
 4       0       49       1
 ...    ..      ...     ...
 111895  0      465       1
 111896  0      524       1
 111897  0       81       1
 111898  0      424       1
 111899  0      451       1
 
 [11625 rows x 3 columns],
 0          63
 1          66
 2           9
 3          59
 4          49
          ... 
 111895    465
 111896    524
 111897     81
 111898    424
 111899    451
 Name: feature, Length: 11625, dtype: int64,
 pandas.core.series.Series)

As we can see this is a `pandas.core.series.Series`, we can get the mean by `pandas.core.series.Series.mean()`

In [13]:
sample_data["feature"].mean()

175.7232688172043

For getting the mean values of all the clasess with all the classes at once, we just need to difine a nested for loop. The first loop iterating over the columns and the second loop iterating over for the classes or `len(data[0].unique())`

Lets first make an empty array of this shape `(classes , columns)`

In [14]:
mean = np.empty(shape = 12)

mean

array([3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323,
       3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323, 3.5e-323])

`numpy.empty()`. uses the first element as the actual empty data and the other as the pointed values by the first element. This enables to store a very large amont of empty array in the sapce of only $1$ data. 

Now iterating the nested loop like this we get 

In [15]:
for i in range(1 , 13):
    mean[i - 1] = data[data["target"] == i]["feature"].mean()
    
mean

array([175.72326882, 168.53588652, 163.95544086, 156.8856    ,
       160.53729032, 158.20328889, 159.86253763, 160.68782796,
       162.94195556, 165.5168172 , 169.74115556, 183.49083871])

So this is our mean data.

Now lets calculate the variance by the same method.

In [16]:
var = np.empty(shape = 12)

for i in range(1 , 13):
    var[i - 1] = data[data["target"] == i]["feature"].var()
    
var

array([37006.35742909, 33460.68489985, 31729.27433916, 29540.87330138,
       31277.56676571, 29814.43364551, 31631.39197653, 32443.30162833,
       34460.21487216, 34899.29653839, 35897.11514312, 41921.8199651 ])

And we have got our variance data too

Now we just need to put these values to corresponding formulas and get the highest probablities

Lets assume we have a person with height $6$. How do we calculate the gender of this person 

In [17]:
feature = sample_data["feature"]

In [18]:
p_1 = (
    np.exp(
        -(
            (feature[0] - mean[0]) ** 2
        ) / (2 * var[0])
    )
) * (
    1 / ((2 * 3.14 * var[0] ** 2) ** (1 / 2))
)

p_1

9.082051743843819e-06

And we do this same thing for all the values of mean and var which denote different variance

In [19]:
def proc(itera):
    out = np.exp(    
        -(    
            (feature[0] - mean[itera]) ** 2
        ) / (2 * var[itera])
    ) * (        
    1 / ((2 * 3.14 * var[itera] ** 2) ** (1 / 2))
    )

    return out

output = [proc(x) for x in range(12)]

output

[9.082051743843819e-06,
 1.0097295678028104e-05,
 1.0710469898254267e-05,
 1.1636000158617184e-05,
 1.0958188161525514e-05,
 1.1496887509495979e-05,
 1.0876588677150024e-05,
 1.0617522340466199e-05,
 1.001754798766329e-05,
 9.83583003881639e-06,
 9.485025865857851e-06,
 8.005330887113536e-06]

As we can see we got multiple values.

In [20]:
np.argmax(np.array(output))

3

This shows that the number being $3$ is with the highest probablity.

So we pick this up

We do the same thing for all values of data

# 3 | Final 🥯

In [21]:
def gaussian(X_train , Y_train , Y_test):
    mean = np.empty(shape = (len(Y_train.unique())  , 
                             len(X_train.columns())))
    
    var = np.empty(shape = (len(Y_train.unique())  , 
                             len(X_train.columns())))
    
    
    for features in range(1 , len(X_train.columns) + 1):
    
        for classes in range(len(Y_train.unique())):
    
            mean[classes][features - 1] = data[data[0] == str(data[0].unique()[classes])][features].mean()
            var[classes][features - 1] = data[data[0] == str(data[0].unique()[classes])][features].var()

    output = np.zeros((len(Y_train.unique())))

    for feature in range(len(Y_train.unique())):
    
        for classess in range(len(X_train.columns) - 2):
    
            output[feature] += (np.exp(-(np.square(test[classess] - mean[classess][feature])) / (2 * var[classess][feature]))) * (1 / (np.sqrt(2 * 3.14 * np.square(var[classess][feature]))))

    output = np.sort(output)

    return output[-1]

And we just made our one of the simplest `GaussianNB`. 

**THIS IS NOT THE FULL IMPLEMENTATION, IT STILL LACKS MANY FUNCTIONALITIES AND IS VULENRABLE TO MANY EDGE CASES, WE WILL IMPROVE THIS IN THE UPCOMING VERSIONS**

**PLEASE COMMENT DOWN IF I DID ANY MISTAKES, OR IF CAN MAKE THIS MORE CONNECTED TO THE GROUND, OR SUGGESTIONS. YOUR ASSISTS ARE HIGHLY APPRECIABLE**

**THATS IT FOR TODAY GUYS**

**HOPE YOU UNDERSTOOD AND LIKED MY WORK**

**DONT FORGET TO MAKE AN UPVOTE  $:)$**

 
<img src = "https://i.imgflip.com/19aadg.jpg">

**PEACE OUT $!!!$**