<a href="https://www.kaggle.com/code/ayushs9020/training-gpt-0-from-scratch-for-kaggle-report?scriptVersionId=130268860" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# 2023 Kaggle AI Report

<img src = "https://cdn4.iconfinder.com/data/icons/logos-and-brands/512/189_Kaggle_logo_logos-512.png" width = 100px>

This notebook is higly inspired by **[Andrej Karpathy](https://www.youtube.com/@AndrejKarpathy)=>[Let's build GPT : from scratch , in code , spelled out](https://youtu.be/kCc8FmEb1nY)**

The $2023$ $Kaggle$ $AI$ $Report$ is an `analytics competition` that invites participants to `write essays on the state of machine learning in 2023`. The essays should describe `what the community has learned over the past 2 years of working and experimenting` with one of the following seven topics:

* Text data
* Image and/or video data
* Tabular and/or time series data
* Kaggle Competitions
* Generative AI
* AI ethics

The essays `should be well-written and informative`, and they `should provide a comprehensive overview of the state of machine learning` in $2023$. The top essays will be `published in the 2023 Kaggle AI Report`, which will be a `valuable resource for anyone who is interested in learning more about the state of machine learning`.

Here are some additional details about the competition:

|_____|_____|
|---|---
|Prizes| 
||$$$10,000$$
||$$$5,000$$
||$$$2,500$$
|Submission deadline|The deadline for submissions is $June$ $1,$ $2023$.
|Submission format|Essays should be submitted as a `PDF file`.
|Length|Essays should be no more than $5,000$ words in length.
|Judging criteria|Clarity
||Organization
||Accuracy
||Completeness
||Originality 
||Creativity

## GPT-0

$GPT-0$ is a `small`, `simple language model` that was created by `OpenAI` in $2020$. It is a `generative pre-trained transformer` model that was trained on a dataset of text and code. `GPT-0` is `not as powerful` as some of the other language models that have been created by `OpenAI`, but it is still a `valuable tool for research and development`. `GPT-0` has been used to generate text, translate languages, and answer questions. It has also been used to create new forms of art and music. `GPT-0` is a powerful tool that has the potential to change the way we interact with computers

Today we will try to build our own `GPT-0` trained on the `Bhagavad Gita`, and see the results

In [1]:
import numpy as np 
import pandas as pd 

In [2]:
import re

In [3]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [4]:
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/2023-kaggle-ai-report/sample_submission.csv
/kaggle/input/2023-kaggle-ai-report/arxiv_metadata_20230510.json
/kaggle/input/2023-kaggle-ai-report/kaggle_writeups_20230510.csv


# 1 | Data 🚀

Lets get our data into working 

In [5]:
data = pd.read_csv("/kaggle/input/2023-kaggle-ai-report/kaggle_writeups_20230510.csv")
data

Competition Launch Date  \
0        08/03/2010 00:00:00   
1        08/03/2010 00:00:00   
2        08/03/2010 00:00:00   
3        08/03/2010 00:00:00   
4        08/03/2010 00:00:00   
...                      ...   
3122     02/23/2023 17:25:32   
3123     02/23/2023 17:25:32   
3124     02/23/2023 17:25:32   
3125     02/23/2023 17:25:32   
3126     02/23/2023 17:25:32   

                                  Title of Competition  \
0     Chess ratings - Elo versus the Rest of the World   
1     Chess ratings - Elo versus the Rest of the World   
2     Chess ratings - Elo versus the Rest of the World   
3     Chess ratings - Elo versus the Rest of the World   
4     Chess ratings - Elo versus the Rest of the World   
...                                                ...   
3122       Google - Isolated Sign Language Recognition   
3123       Google - Isolated Sign Language Recognition   
3124       Google - Isolated Sign Language Recognition   
3125       Google - Isolated Sign Language Recognition   
3126       Google - Isolated Sign Language Recognition   

                     Competition URL      Date of Writeup  \
0      https://www.kaggle.com/c/2447  11/18/2010 00:06:46   
1      https://www.kaggle.com/c/2447  11/20/2010 04:38:53   
2      https://www.kaggle.com/c/2447  11/23/2010 10:38:23   
3      https://www.kaggle.com/c/2447  11/20/2010 11:27:17   
4      https://www.kaggle.com/c/2447  11/18/2010 02:44:10   
...                              ...                  ...   
3122  https://www.kaggle.com/c/46105  05/02/2023 09:45:01   
3123  https://www.kaggle.com/c/46105  05/02/2023 10:13:31   
3124  https://www.kaggle.com/c/46105  05/02/2023 03:24:28   
3125  https://www.kaggle.com/c/46105  05/02/2023 04:01:15   
3126  https://www.kaggle.com/c/46105  05/02/2023 00:08:37   

                                       Title of Writeup  \
0                 Released: my Source Code and Analysis   
1                          6th place(UriB) by Uri Blass   
2                                7th place - littlefish   
3                     3rd place: Chessmetrics - Variant   
4                     2nd place: TrueSkill Through Time   
...                                                 ...   
3122                         49th place silver solution   
3123                                10th place solution   
3124  Solution - Single transformer without val dataset   
3125                       Top 8% Bronze Medal Solution   
3126  44th Place Silver - How To Improve Best Public...   

                                                Writeup  \
0     <p>I had a lot of fun with this competition an...   
1     <P>I calculated rating for every player in mon...   
2     I'm a little surprised I ended up in the top-1...   
3     <p><span id="post_text_content_1230"><div dir=...   
4     Wow, this is a surprise! I looked at this comp...   
...                                                 ...   
3122  <p>Thank you Kaggle and Pop sign for hosting t...   
3123  <blockquote>\n  <p>First, I would like to than...   
3124  <p>Thanks to the organisers of the PopSign Gam...   
3125  <blockquote>\n  <p><strong>Many congratulation...   
3126  <p>Thank you Kaggle, Kagglers, PopSign, and Pa...   

                                           Writeup URL  
0         https://www.kaggle.com/c/2447/discussion/185  
1         https://www.kaggle.com/c/2447/discussion/192  
2         https://www.kaggle.com/c/2447/discussion/194  
3         https://www.kaggle.com/c/2447/discussion/193  
4         https://www.kaggle.com/c/2447/discussion/186  
...                                                ...  
3122  https://www.kaggle.com/c/46105/discussion/406426  
3123  https://www.kaggle.com/c/46105/discussion/406434  
3124  https://www.kaggle.com/c/46105/discussion/406346  
3125  https://www.kaggle.com/c/46105/discussion/406354  
3126  https://www.kaggle.com/c/46105/discussion/406302  

[3127 rows x 7 columns]

At this point we will only focus on the `Writeup` column, we will try to access/process more information in the upcoming versions

Our data is distributed in a `CSV File`. We need to extract our data in a `txt File` as a large corpus of data 

In [6]:
data["Writeup"]

0       <p>I had a lot of fun with this competition an...
1       <P>I calculated rating for every player in mon...
2       I'm a little surprised I ended up in the top-1...
3       <p><span id="post_text_content_1230"><div dir=...
4       Wow, this is a surprise! I looked at this comp...
                              ...                        
3122    <p>Thank you Kaggle and Pop sign for hosting t...
3123    <blockquote>\n  <p>First, I would like to than...
3124    <p>Thanks to the organisers of the PopSign Gam...
3125    <blockquote>\n  <p><strong>Many congratulation...
3126    <p>Thank you Kaggle, Kagglers, PopSign, and Pa...
Name: Writeup, Length: 3127, dtype: object

We just cant concatenate all of this into a single string. Let me show you how the data actually looks like 

In [7]:
print(data["Writeup"][0])

<p>I had a lot of fun with this competition and learned a lot about ratings systems.</p>
<div>Sadly, I only came 18th :)</div>
<div>If you're interested, you can download all of my code and&nbsp;analysis&nbsp;from my github repo:&nbsp;https://github.com/jbrownlee/ChessML</div>
<div>There are implementations of a few rating systems (elo, glicko, chessmetrics, etc) and many attempts at improving them (a nice little experimentation framework).</div>
<div>Thanks all. Looking forward to the next big comp!</div>
<div>jasonb</div>


You can note that there are many of the `HTML tags` and other links provided in the data. We do not need these links, So it would be great if we juse remove all of this 

In [8]:
print(re.sub(':' , " " , re.sub(';' , ' ' , re.sub('&nbsp' , "" , 
       (re.sub(r'http\S+', ' ', 
               (re.compile(r'<.*?>').sub("" ,data["Writeup"][0]))))))))

I had a lot of fun with this competition and learned a lot about ratings systems.
Sadly, I only came 18th  )
If you're interested, you can download all of my code and analysis from my github repo   
There are implementations of a few rating systems (elo, glicko, chessmetrics, etc) and many attempts at improving them (a nice little experimentation framework).
Thanks all. Looking forward to the next big comp!
jasonb


In [9]:
emoj = re.compile("["
    u"\U0001F600-\U0001F64F"  # emoticons
    u"\U0001F300-\U0001F5FF"  # symbols & pictographs
    u"\U0001F680-\U0001F6FF"  # transport & map symbols
    u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
    u"\U00002500-\U00002BEF"  # chinese char
    u"\U00002702-\U000027B0"
    u"\U00002702-\U000027B0"
    u"\U000024C2-\U0001F251"
    u"\U0001f926-\U0001f937"
    u"\U00010000-\U0010ffff"
    u"\u2640-\u2642" 
    u"\u2600-\u2B55"
    u"\u200d"
    u"\u23cf"
    u"\u23e9"
    u"\u231a"
    u"\ufe0f"  # dingbats
    u"\u3030"
    u"\u2028"
    "\x08"
    u"\u200a"
    u"\u200b"
                  "]+", re.UNICODE)

In [10]:
text = str()
for i in data["Writeup"]: 
    k = re.sub(':' , " " , 
               re.sub(';' , ' ' , 
                      re.sub('&nbsp' , '' , 
                             (re.sub(r'http\S+', ' ', 
                                     (re.compile(r'<.*?>').sub("" , 
                                                               str(i))))))))
    k = emoj.sub(r'' , k)
    text += k

Now we have a large corpus of data, now we can finally train a model 

# 2 | Embeddings/Tokenizing 🔢

Okay, so just hear me out. First thing to notice, we cannot just put letters into a model and expect it to undertand everything. No, We need to somehow make this characters into numbers, somehow, we really dont know how, but somehow, we will do that. 

Okay so we know what characters we have, like we know, all the characters will fall in the `English Alphabet`, maybe we find some extra characters like, `"," , "." , etc`. So what if we number them like that only. 

Lets assume we have a letter like `Optimus Prime`, we know that in the `English Alphabet` ,  `O`  comes at `15`, so we can number `O` as `15` and like this only the whole sequence becomes something like this 

|_____|_____
|---|---
|O|15
|p|42
|t|46
|i|35
|m|39
|u|47
|s|45
| |0
|P|16
|r|44
|i|35
|m|39
|e|31

We call this numerical representation of a `str`, **Embedding/Tokenizing**

What we did here was `character encoding` , means we were taking every character to be distinct of each other, or be independent to each character. 

There are other types of possible encoding available, such as `Bag Of Words , TF-IDF , Word2Vec , Glove`. There are more available like **[Sentence Piece by Google](https://github.com/google/sentencepiece)**  or **[Tik Token by OpenAI](https://github.com/openai/tiktoken)**
 , which you can try 
So now we have an intution of what we have to do, now we need to code that intution. Lets first get all the unique values of this corpus we have 

In [11]:
print("Unqiue values of the corpus : " , set(text))
print("---------------------------------------------------------------------------------------------")
print("Sorted Unique values of the corpus : " , sorted(list(set(text))))

Unqiue values of the corpus :  {'s', '④', '[', 'ল', '२', 'Ⅰ', 'K', 'ई', '/', 'V', '·', 'о', 'ú', '−', 'ீ', '$', 'О', 'J', "'", '௧', '¯', 'ó', 'F', 'O', 't', 'q', 'β', '^', '×', 'h', '↓', 'ঘ', '4', 'R', '•', 'õ', 'μ', 'Q', 'U', '„', '—', '¿', 'k', 'ு', '␣', '∃', 'D', '→', '※', '௦', 'g', '?', 'C', 'স', '№', '∈', 'Γ', 'é', '∗', '#', 'л', 'ফ', '≥', '(', '্', 'Π', '②', '\\', '∵', 'ä', 'Å', 'A', '²', '¶', 'x', 'N', 'к', '०', '∝', '∠', 'è', 'f', 'α', '१', 'ô', '३', '\r', 'É', 'W', 'ы', '’', 'ষ', 'δ', '४', 'š', 'খ', 'Ø', 'L', '∧', 'ঁ', '1', '”', '@', 'd', 'a', 'M', 'б', 'у', 'b', 'Δ', 'u', '¼', 'Y', 'щ', ' ', 'а', 'ক', '√', ')', 'н', 'ł', 'м', '≈', 'Л', 'Z', '≤', 'æ', 'শ', 'H', '°', 'ь', '…', '+', 'я', 'λ', 'З', 'T', '\t', 'হ', '~', '&', '।', '①', 'S', 'п', '%', 'р', 'য', '९', 'й', 'ч', 'д', 'т', 'å', '⅓', '±', '=', '2', '6', 'х', '.', 'κ', '|', 'v', '८', 'е', 'ц', '⊿', 'и', 'ू', 'w', 'в', '‚', 'ṣ', '–', '*', '∑', 'G', 'দ', 'ș', '③', 'r', '-', '0', 'P', '‘', 'Ж', 'А', '8', 'Ⅱ', 'प', '↑', '≠', 

In [12]:
characters = sorted(list(set(text)))

Now we will try to map these characters with some specific numbers 

In [13]:
stoi = {ch:i for i,ch in enumerate(characters)}
itos = {i:ch for i,ch in enumerate(characters)}

In [14]:
print("Mapping of characters to numbers : " , stoi)
print("---------------------------------------------------------------------------------------------")
print("Mapping of numbers to characters : " , itos)

Mapping of characters to numbers :  {'\t': 0, '\n': 1, '\r': 2, ' ': 3, '!': 4, '"': 5, '#': 6, '$': 7, '%': 8, '&': 9, "'": 10, '(': 11, ')': 12, '*': 13, '+': 14, ',': 15, '-': 16, '.': 17, '/': 18, '0': 19, '1': 20, '2': 21, '3': 22, '4': 23, '5': 24, '6': 25, '7': 26, '8': 27, '9': 28, '=': 29, '?': 30, '@': 31, 'A': 32, 'B': 33, 'C': 34, 'D': 35, 'E': 36, 'F': 37, 'G': 38, 'H': 39, 'I': 40, 'J': 41, 'K': 42, 'L': 43, 'M': 44, 'N': 45, 'O': 46, 'P': 47, 'Q': 48, 'R': 49, 'S': 50, 'T': 51, 'U': 52, 'V': 53, 'W': 54, 'X': 55, 'Y': 56, 'Z': 57, '[': 58, '\\': 59, ']': 60, '^': 61, '_': 62, '`': 63, 'a': 64, 'b': 65, 'c': 66, 'd': 67, 'e': 68, 'f': 69, 'g': 70, 'h': 71, 'i': 72, 'j': 73, 'k': 74, 'l': 75, 'm': 76, 'n': 77, 'o': 78, 'p': 79, 'q': 80, 'r': 81, 's': 82, 't': 83, 'u': 84, 'v': 85, 'w': 86, 'x': 87, 'y': 88, 'z': 89, '{': 90, '|': 91, '}': 92, '~': 93, '«': 94, '®': 95, '¯': 96, '°': 97, '±': 98, '²': 99, '´': 100, '¶': 101, '·': 102, '»': 103, '¼': 104, '½': 105, '¿': 106,

Now we will make $2$ functions, `encoder , decoder`, 

Encoder will take `str` as an input and return the corresponding embedding

Decoder will take `embedding representation` as an input and returnthe corresponding `str` value

In [15]:
encoder = lambda s: [stoi[c] for c in s]
decoder = lambda l: ''.join([itos[i] for i in l])

Lets try our old example `Optimus Prime `

In [16]:
encoder("Optimus Prime")

[46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68]

In [17]:
decoder(encoder("Auto Bots ! , ROll OUT"))

'Auto Bots ! , ROll OUT'

In [18]:
data = torch.tensor(np.array(encoder(text)))

# 3 | Train-Test Split 🚃
$Training$ $data$ is used to `teach a machine learning model` how to perform a specific task. $Testing$ $data$ is used to `evaluate the performance of a trained model`. The training and testing data should be representative of the data that the model will be used on in the real world. High-quality data is essential for training and evaluating machine learning models in $NLP$. By using high-quality data, you can ensure that your models are accurate and effective.

We will divide our data into $1:9$ ratio for `testing and training` respectively 

In [19]:
train = data[:int(0.9 * len(data))]
val = data[int(0.9 * len(data)):]

# 4 | Next Character Prediction ⏭️

Lets take the same example 

In [20]:
encoder("I am Optimus Prime")

[40, 3, 64, 76, 3, 46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68]

What we do is 
* **We first only feed the letter $40$ to the model**
* **Then we try to predict the next letter means $3$**
* **Then We get some error**
* **We then change the weights and biases according to the optimizer**
* **Then we repeat the process with the letter $40 , 3$ and try to predict $64$**
* **We repeat the process till the lists end** 

Now lets assume we have a very long sentence like 

```
But no, I won't slow down
Hold my own right now
In the zone I found
Finna blow this sound
As I grow this crowd
You all know me now
Being known, call it clout
Better watch the fuck out, yeah

To be the best
Must be different than the rest
Must commit to every test
Turning noes into a yes
Fuck the haters, second guess
While you know what you do best
Take the risk and take the debt
Count the cards and rig the deck, yeah
```

If we encode this, we get 

In [21]:
sample_text = '''But no, I won't slow down
Hold my own right now
In the zone I found
Finna blow this sound
As I grow this crowd
You all know me now
Being known, call it clout
Better watch the fuck out, yeah

To be the best
Must be different than the rest
Must commit to every test
Turning noes into a yes
Fuck the haters, second guess
While you know what you do best
Take the risk and take the debt
Count the cards and rig the deck, yeah'''

In [22]:
np.array(encoder(sample_text))

array([33, 84, 83,  3, 77, 78, 15,  3, 40,  3, 86, 78, 77, 10, 83,  3, 82,
       75, 78, 86,  3, 67, 78, 86, 77,  1, 39, 78, 75, 67,  3, 76, 88,  3,
       78, 86, 77,  3, 81, 72, 70, 71, 83,  3, 77, 78, 86,  1, 40, 77,  3,
       83, 71, 68,  3, 89, 78, 77, 68,  3, 40,  3, 69, 78, 84, 77, 67,  1,
       37, 72, 77, 77, 64,  3, 65, 75, 78, 86,  3, 83, 71, 72, 82,  3, 82,
       78, 84, 77, 67,  1, 32, 82,  3, 40,  3, 70, 81, 78, 86,  3, 83, 71,
       72, 82,  3, 66, 81, 78, 86, 67,  1, 56, 78, 84,  3, 64, 75, 75,  3,
       74, 77, 78, 86,  3, 76, 68,  3, 77, 78, 86,  1, 33, 68, 72, 77, 70,
        3, 74, 77, 78, 86, 77, 15,  3, 66, 64, 75, 75,  3, 72, 83,  3, 66,
       75, 78, 84, 83,  1, 33, 68, 83, 83, 68, 81,  3, 86, 64, 83, 66, 71,
        3, 83, 71, 68,  3, 69, 84, 66, 74,  3, 78, 84, 83, 15,  3, 88, 68,
       64, 71,  1,  1, 51, 78,  3, 65, 68,  3, 83, 71, 68,  3, 65, 68, 82,
       83,  1, 44, 84, 82, 83,  3, 65, 68,  3, 67, 72, 69, 69, 68, 81, 68,
       77, 83,  3, 83, 71

That comes out to be a very large number, it is not good to give this much large size of text to the model, so what we do is, we choose a random susbset of fixed size from this data and then train the model, lets assume we take a block size of $8$ for this then 

In [23]:
block_size = 8
train[:block_size]

tensor([40,  3, 71, 64, 67,  3, 64,  3])

Now lets assume we have reached the letter $3$, then we would get an error, cause at this point we do not have any ground truth to compare our predictions of the model. To counter this problem, we take an extra element of the block size

In [24]:
train[:block_size + 1]

tensor([40,  3, 71, 64, 67,  3, 64,  3, 75])

# 5 | Batch Size 📏

Now as we are using $GPUs/TPUs$, we can do parallel processing at a very largers extent as compared to $CPU$. So what we do is we simustaniously send batches of data for training to the model or for processing. 

Lets assume we pass a `batch_size` of $4$.

In [25]:
x = torch.randint(len(train) - 8 , (4,))

In [26]:
torch.stack([train[i : i + 8] for i in x])

tensor([[52, 82, 68, 67,  3, 35, 64, 83],
        [83,  3, 78, 77,  3, 83, 71, 68],
        [81, 64, 72, 77, 72, 77, 70,  3],
        [75, 68, 67,  3, 64, 83,  3, 83]])

Now lets asusme we take this as 

In [27]:
torch.stack([train[i + 1: i + 8] for i in x])

tensor([[82, 68, 67,  3, 35, 64, 83],
        [ 3, 78, 77,  3, 83, 71, 68],
        [64, 72, 77, 72, 77, 70,  3],
        [68, 67,  3, 64, 83,  3, 83]])

Noticed one this...?

We can see the ground truth values of the first `tensor` in second `tensor`. 

So we can name these tensors to be `X` and `y` respectively 

In [28]:
X = torch.stack([train[i : i + 8] for i in x])
y = torch.stack([train[i + 1: i + 8] for i in x])

So lets create a function `batch` that return batchs according to the batch size.

In [29]:
def batch(dataset , batch_size = 4):
    
    data = train if dataset == "train" else val
    
    index = torch.randint(len(data) - block_size , 
                          (batch_size , ))
    
    X = torch.stack([data[i : i + block_size] for i in index])
    y = torch.stack([data[i + 1 : i + block_size + 1] for i in index])
    
    return X , y

In [30]:
X_batch , y_batch = batch("train")

# 6 | Bigram Model 2️⃣

Bigram is a simple model, that tries to predict the next word on the knowledge of the previous word. Lets assume we have the text

In [31]:
sample_text = "Optimus Prime"

In [32]:
for char1 , char2 in zip(sample_text , sample_text[1:]):
    print(char1 , char2)

O p
p t
t i
i m
m u
u s
s  
  P
P r
r i
i m
m e


So here, the model will try to predict the word `p` when known the word `O` , next it will try to predict the word `t` when known the word `p` and so on. 

To do so, first we create a token embedding table, a table that will be the reference to the embeddings of the table. 

But what is a `embedding table...?`

Embedding table in short is a vector representation of a letter in a `n-dimensional` space. We can understand this better using the `Word2Vec` conversion, given by $Google$. Lets assume we have a word `king` and another word `royalty`. We know that these words are very much related to eacher other, means if we try to plot these $2$ words as some vectors in a $2-dimension$ space, those vectors are likely to be close to each other. 

Now lets try to understand this for a larger set of data of text. At the time of intializing we do not know any relations between any of the words, as we go through the corpus of data and find the words that are used in a particular combination frequently, we slowly change the `vector representation` of those words to be close to each other. We took $2-dimension$ to be just example, we actually take a bigger representation of words. Here we will take the representation to be $len(characters)-dimension$

In [33]:
embed_table = nn.Embedding(len(characters) , len(characters))
embed_table

Embedding(273, 273)

Lets assume we have a character at index $8$, If we look at the $8^{th}$ index, we get this 

In [34]:
embed_table(torch.tensor(8))

tensor([-2.2019, -0.7400,  0.2161,  0.2369,  1.4337, -1.3968, -0.3926,  1.3093,
        -0.0719,  0.6677, -1.3115, -2.0803, -0.9278,  1.2298,  0.7602,  0.2774,
        -0.0898,  0.1217, -0.2180, -0.6417,  0.0776,  0.8967,  0.0752, -0.2179,
        -0.5716,  0.1288, -0.4691, -0.6883, -0.7989, -0.5139, -1.8098, -0.7210,
         2.0724,  0.4572,  0.6601,  0.6612,  1.8767,  0.8409,  0.0617,  1.3419,
         0.0147, -0.5675,  0.4361,  1.3166,  1.4208,  0.2412, -0.9601, -0.7562,
         0.5931,  2.7300, -2.7877, -0.0796, -1.3813, -0.1329, -0.5752, -0.3871,
        -0.7440,  0.7907, -0.4577,  1.1250,  1.8086, -0.4188,  1.0672, -0.2765,
         1.3156, -1.0533, -1.0530, -1.7932,  0.7555, -0.8104, -1.3214, -0.7660,
         2.1036,  2.0319,  0.0198,  0.0476, -1.0088,  1.4219, -0.5770, -0.0095,
         0.5293,  0.2045, -0.4353, -0.1671,  0.4953,  0.2441,  0.4903, -0.5162,
         0.2073, -0.4335,  2.6133, -3.0452,  0.6773, -0.0258, -0.2770, -1.3284,
        -0.5979, -0.2127, -0.8755, -1.17

* We defind the `BigramLanguageModel` with a class inherited from `nn.Module`. **Remeber to specify a forward function when passing the `nn.Module`**. 
* The we create the embedding table.
* We define the targets and predictions a little differnet by changing thier dimensions, as `pytoroch.nn.functional.corss_entrpy` do not accept this type of shape.
* The we predict, using the softmax function. 
* Then we calculate the loss

Its very simple naa

In [35]:
vs = len(characters)

class BigramLanguageModel(nn.Module):

    def __init__(self, vs):
        super().__init__()
        
        self.token_embedding_table = nn.Embedding(vs, vs)

    def forward(self, idx, targets=None):

        logits = self.token_embedding_table(idx)
        
        if targets is None:
            
            loss = None
        
        else:
            
            B, T, C = logits.shape
            logits = logits.view(B * T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        
        for _ in range(max_new_tokens):
        
            logits, loss = self(idx)
            logits = logits[:, -1, :] 
        
            probs = F.softmax(logits, dim=-1) 
        
            idx_next = torch.multinomial(probs, num_samples=1) 
        
            idx = torch.cat((idx, idx_next), dim=1) 
        
        return idx

m = BigramLanguageModel(vs)
logits, loss = m(X_batch , y_batch)

Now lets see how our model performed 

In [36]:
loss

tensor(6.0353, grad_fn=<NllLossBackward0>)

Not bad $!!!!$

In [37]:
print(decoder(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))

c∞».δ'I௦⑤≒␣I∠ீ²șà⑤¶iகAå1x␣কОaप²gх|¼নóèIü[θÉW


This is how a text output from our model looks like

# 7 | Training 🚃

Now lets train this model for around $100$ epochs

In [38]:
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [39]:
batch_size = 32
for steps in range(1000): 
    
    xb, yb = batch('train')
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


5.415089130401611


In [40]:
print(decoder(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

∑õ≒ηZa±१@KG५?æfW␣খX\Øঘ③ôiQ∃লμx४ப≈/1еff²ș≥∞&ηⅢ√∈ğjদLM&fç∧'₂I␣»eq?æÃप6п|②ΠVV²Éd¿'ûаğ↓Y~γ∵ ≈mpс
→
м$াω₂è≥α३ьbকy®2»пீ´≥κPLH०}яX½%Ж४ğখ९αО௦ঁ①
,iО+⑤²`O¶Ãé∃а௦хி


And I totally understand this language $:)$

# 8 | Masking 

Letss asume we have the same text `Optimus Prime `

In [41]:
encoder("Optimus Prime")

[46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68]

In the Bigram we were only taking into account of the precessor of the predicted element. 

In our next approach we try to predict the element, having the knowledge of all the preceeding elements. 

For this first we need to mask the elements. Let me show you what I mean by masking 

In [42]:
sample = [encoder("Optimus Prime") for _ in "Optimus Prime"]
sample

[[46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68],
 [46, 79, 83, 72, 76, 84, 82, 3, 47, 81, 72, 76, 68]]

In [43]:
torch.tril(torch.tensor(sample))

tensor([[46,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [46, 79,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [46, 79, 83,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [46, 79, 83, 72,  0,  0,  0,  0,  0,  0,  0,  0,  0],
        [46, 79, 83, 72, 76,  0,  0,  0,  0,  0,  0,  0,  0],
        [46, 79, 83, 72, 76, 84,  0,  0,  0,  0,  0,  0,  0],
        [46, 79, 83, 72, 76, 84, 82,  0,  0,  0,  0,  0,  0],
        [46, 79, 83, 72, 76, 84, 82,  3,  0,  0,  0,  0,  0],
        [46, 79, 83, 72, 76, 84, 82,  3, 47,  0,  0,  0,  0],
        [46, 79, 83, 72, 76, 84, 82,  3, 47, 81,  0,  0,  0],
        [46, 79, 83, 72, 76, 84, 82,  3, 47, 81, 72,  0,  0],
        [46, 79, 83, 72, 76, 84, 82,  3, 47, 81, 72, 76,  0],
        [46, 79, 83, 72, 76, 84, 82,  3, 47, 81, 72, 76, 68]])

For predicting $66$ , we should not need any knowledge of the letters after $66$, similarly for predictiing using $38 , 66$, we should not take into accoun the upcoming values after $70$.

Thats how attention mechanism at its core work. It has more than meets the eye, and we will get to that part soon 

One more thing to say, we actually take the mean of all the values before that number to predict

In [44]:
sample = torch.tril(torch.tensor(sample))
sample = sample / torch.sum(sample , 1 , keepdim = True )
sample

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.3680, 0.6320, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.2212, 0.3798, 0.3990, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.1643, 0.2821, 0.2964, 0.2571, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.1292, 0.2219, 0.2331, 0.2022, 0.2135, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.1045, 0.1795, 0.1886, 0.1636, 0.1727, 0.1909, 0.0000, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.0881, 0.1513, 0.1590, 0.1379, 0.1456, 0.1609, 0.1571, 0.0000, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.0876, 0.1505, 0.1581, 0.1371, 0.1448, 0.1600, 0.1562, 0.0057, 0.0000,
         0.0000, 0.0000, 0.0000, 0.0000],
        [0.0804,

In [45]:
sa = torch.randint(0 , 10 , (13 , 13)).float()
out = sample @ sa
out

tensor([[3.0000, 8.0000, 5.0000, 1.0000, 2.0000, 8.0000, 0.0000, 0.0000, 6.0000,
         3.0000, 8.0000, 0.0000, 2.0000],
        [4.2640, 6.7360, 3.7360, 2.8960, 2.6320, 4.2080, 1.2640, 3.7920, 7.2640,
         1.7360, 2.9440, 1.8960, 3.2640],
        [6.1538, 4.8462, 3.0433, 2.9375, 1.9808, 2.9279, 3.9519, 5.8702, 5.5625,
         1.0433, 4.5625, 4.3317, 1.9615],
        [5.0857, 5.1429, 2.2607, 2.6964, 2.5000, 4.2321, 3.4500, 5.3893, 5.6750,
         1.8036, 3.6464, 3.9893, 3.0000],
        [5.4944, 4.8989, 2.4185, 3.8287, 3.6742, 4.1826, 4.6348, 4.4522, 5.5309,
         1.4185, 3.7219, 4.6320, 2.3596],
        [5.2091, 4.9182, 2.3386, 3.0977, 2.9727, 3.7659, 4.8955, 5.1295, 4.6659,
         1.3386, 4.5386, 5.2750, 2.6727],
        [5.6475, 5.0881, 2.2854, 4.0249, 2.5057, 3.4885, 4.7548, 5.5805, 5.3467,
         1.9138, 4.1398, 4.7605, 3.5096],
        [5.6438, 5.0705, 2.3067, 4.0190, 2.5143, 3.5086, 4.7276, 5.6000, 5.3448,
         1.9200, 4.1219, 4.7505, 3.5295],
        [5.7552,

What I did was just caluclating mean with a simple trick that works everytime 

Now lets move to the major part of the `self-attention`. We first define our `batch-size and dimesnions of the vector `

In [46]:
B,T,C = 4,8,32
x = torch.randn(B,T,C)
x

tensor([[[-0.9628,  0.2782, -0.3335,  ..., -0.1825,  0.9069, -0.1162],
         [ 1.2995, -0.6483, -0.0462,  ..., -0.7860, -0.0490,  0.2601],
         [-0.8922,  0.2428,  0.6072,  ..., -0.4705,  0.5289,  1.8463],
         ...,
         [ 0.7247,  0.2804,  1.5758,  ..., -0.0284, -0.8264, -0.4249],
         [-0.2753,  0.8710, -2.1129,  ..., -0.5784,  0.1110,  0.4400],
         [ 1.5303,  0.9671,  1.6280,  ...,  1.0830,  0.1611, -0.6250]],

        [[-0.1395,  1.3306, -0.5951,  ..., -0.7618, -0.5901, -0.4123],
         [ 0.3400,  1.0596, -1.6983,  ...,  0.8917,  1.7343,  0.5231],
         [ 1.8180, -0.5812,  0.5071,  ...,  1.3931,  1.5593,  0.3988],
         ...,
         [-1.7151, -1.4212,  0.3235,  ..., -1.1360,  1.9127,  0.4738],
         [ 0.7044, -0.0660, -1.4566,  ...,  0.3886,  1.9928,  0.3954],
         [-0.1384, -0.2740,  1.6612,  ..., -0.4448, -0.3559,  1.0197]],

        [[-1.3110, -0.0785, -0.2089,  ...,  0.0617,  0.9952, -0.1981],
         [-0.8248, -0.5622, -0.4220,  ..., -0

What we do is we first define the size of our head 

In [47]:
head_size = 16

Then we use the single representations of the vectors to reflect themselves into $2$ forms, 

* Query - What are we looking for 
* Key - What do we have 

For the `key` and `query` we make `Linear modules`

In [48]:
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
k = key(x)
q = query(x)

Till this `keys` and `queries` were not communicating at all, but now we will mutiply them 

In [49]:
weights = q @ k.transpose(-2 , -1)
weights

tensor([[[-1.0488e+00, -1.9755e+00,  2.2960e+00, -1.8524e-01,  2.1425e+00,
           2.7714e-01,  9.5622e-01,  1.0015e+00],
         [-4.0285e-01, -5.1887e-02,  2.1795e-01,  3.5093e-02,  7.5728e-01,
           2.9731e-01,  9.2080e-01, -9.7288e-01],
         [ 7.6146e-01,  3.4029e-01,  1.9103e+00,  1.0139e+00, -7.8808e-01,
           5.2168e-01, -9.6471e-01, -3.4202e+00],
         [-3.3372e-01, -2.1511e-01,  1.8498e+00,  1.8142e-01,  5.2468e-01,
          -6.0288e-01,  4.1022e-01, -7.1222e-01],
         [-1.8431e-01,  3.2001e-01, -1.4204e+00, -6.3495e-01,  2.2434e-02,
          -1.7417e+00,  1.3320e+00,  5.3997e-01],
         [ 1.1307e+00, -2.3602e-03, -2.0479e+00, -2.2833e-01, -6.4027e-01,
          -1.3606e+00, -5.8966e-01,  1.8772e+00],
         [ 1.1210e+00,  1.0175e+00, -1.5535e+00,  1.2079e+00, -2.1571e+00,
          -8.6790e-01, -8.5228e-01, -1.5158e+00],
         [ 6.7532e-01, -3.6301e-01, -1.9629e+00, -6.0438e-02, -1.7116e+00,
           9.7961e-01, -8.2938e-02,  4.9876e+00]],

Now we mask the `weights` accordingly 

In [50]:
tril = torch.tril(torch.ones(T , T))
weights = weights.masked_fill(tril == 0 , float("-inf"))
weights

tensor([[[-1.0488e+00,        -inf,        -inf,        -inf,        -inf,
                 -inf,        -inf,        -inf],
         [-4.0285e-01, -5.1887e-02,        -inf,        -inf,        -inf,
                 -inf,        -inf,        -inf],
         [ 7.6146e-01,  3.4029e-01,  1.9103e+00,        -inf,        -inf,
                 -inf,        -inf,        -inf],
         [-3.3372e-01, -2.1511e-01,  1.8498e+00,  1.8142e-01,        -inf,
                 -inf,        -inf,        -inf],
         [-1.8431e-01,  3.2001e-01, -1.4204e+00, -6.3495e-01,  2.2434e-02,
                 -inf,        -inf,        -inf],
         [ 1.1307e+00, -2.3602e-03, -2.0479e+00, -2.2833e-01, -6.4027e-01,
          -1.3606e+00,        -inf,        -inf],
         [ 1.1210e+00,  1.0175e+00, -1.5535e+00,  1.2079e+00, -2.1571e+00,
          -8.6790e-01, -8.5228e-01,        -inf],
         [ 6.7532e-01, -3.6301e-01, -1.9629e+00, -6.0438e-02, -1.7116e+00,
           9.7961e-01, -8.2938e-02,  4.9876e+00]],

Now if we calucalate the `softmax` of these, we get 

In [51]:
weights = F.softmax(weights , dim = -1)
weights

tensor([[[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00],
         [4.1315e-01, 5.8685e-01, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00],
         [2.0787e-01, 1.3642e-01, 6.5571e-01, 0.0000e+00, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00],
         [7.8882e-02, 8.8816e-02, 7.0026e-01, 1.3204e-01, 0.0000e+00,
          0.0000e+00, 0.0000e+00, 0.0000e+00],
         [2.0776e-01, 3.4402e-01, 6.0356e-02, 1.3239e-01, 2.5548e-01,
          0.0000e+00, 0.0000e+00, 0.0000e+00],
         [5.3374e-01, 1.7189e-01, 2.2227e-02, 1.3712e-01, 9.0826e-02,
          4.4196e-02, 0.0000e+00, 0.0000e+00],
         [2.9629e-01, 2.6718e-01, 2.0428e-02, 3.2320e-01, 1.1171e-02,
          4.0548e-02, 4.1186e-02, 0.0000e+00],
         [1.2750e-02, 4.5141e-03, 9.1146e-04, 6.1090e-03, 1.1719e-03,
          1.7285e-02, 5.9731e-03, 9.5129e-01]],

        [[1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.00

And this is what we wanted 

Then we create another `Linear module` named `value`. and multiply that with  the output 

In [52]:
value = nn.Linear(C , head_size , bias = False)
v = value(x)

In [53]:
output = weights @ v
output

tensor([[[-2.1947e-01, -9.6344e-01,  2.0390e-01, -2.7194e-01,  6.9707e-01,
           4.6773e-02, -9.5537e-02,  1.2793e-02,  1.5719e-02, -8.0422e-01,
          -5.1110e-01, -4.7746e-02, -1.2338e-01, -4.4725e-01, -2.1052e-01,
           3.9645e-01],
         [ 6.1186e-01, -2.9562e-01,  4.0099e-01, -4.8974e-01,  8.2172e-02,
          -2.4239e-01, -1.4575e-01,  3.5189e-01, -7.5760e-02, -2.9942e-01,
          -4.6253e-01,  2.7902e-01,  1.0354e-01, -6.4632e-02, -1.1827e-02,
           1.7334e-02],
         [ 3.2428e-01, -1.0614e-01,  5.0512e-01, -3.4286e-01,  3.5453e-02,
          -5.3293e-01, -8.5673e-01, -2.3647e-01, -2.5600e-01, -7.5170e-01,
           2.5782e-01, -6.5639e-01, -7.9225e-01, -1.0354e-01,  5.5644e-02,
           3.8767e-01],
         [ 2.6208e-01, -3.8796e-02,  4.7226e-01, -2.9768e-01, -1.2949e-01,
          -5.2271e-01, -8.1979e-01, -2.1124e-01, -3.4378e-01, -7.4472e-01,
           2.4796e-01, -6.7601e-01, -8.4394e-01, -5.0921e-02,  5.4623e-02,
           4.5032e-01],
    

If we calculate the variance of these values, they are very high

In [54]:
k.var() , q.var() , weights.var()

(tensor(0.3086, grad_fn=<VarBackward0>),
 tensor(0.3413, grad_fn=<VarBackward0>),
 tensor(0.0434, grad_fn=<VarBackward0>))

To scale them down, divide them by their $\sqrt{head_-size}$

In [55]:
wei = q @ k.transpose(-2, -1) * head_size**-0.5

This actually solved one more problem, as the varianace increases, the softmax sharpens, and may reach exact $1 , 0$ values. Scaling stops the softmax to do so 

Now we just put all of this into a class

In [56]:
class Head(nn.Module):

    def __init__(self, head_size):
        
        super().__init__()
        
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        
        self.register_buffer('tril', 
                             torch.tril(torch.ones(block_size, 
                                                   block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        B,T,C = x.shape
        
        k = self.key(x)
        q = self.query(x)
        
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 
        wei = wei.masked_fill(self.tril[:T, :T] == 0, 
                              float('-inf'))
        
        wei = F.softmax(wei, dim=-1)
        
        wei = self.dropout(wei)
        
        v = self.value(x)
        out = wei @ v 
        
        return out

Now we do this for different number of heads

In [57]:
class MultiHeadAttention(nn.Module):

    def __init__(self, num_heads, head_size):
        
        super().__init__()
        
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

This is actually not $GPT-0$, its not even close to that model, but we made this to get an intution of how we will make the $GPT-0$ model. 

The $GPT-0$ model will be upadted soon in this notebook, in around $1-2$ days

# 8 | TO DO LIST 📝

```
# ADD ATTENTION MECHANISM

# ADD WANDB SUPPORT 

# IMPORVE THE RESULTS
```

# 9 | End Yayyyyyyyyyyyy :) 🥳🎊
**THAT IT FOR TODAY GUYS**

**WE WILL IMPROVE THIS IN UPCOMING VERSIONS**

**PLEASE COMMENT YOUR THOUGHTS, HIHGLY APPRICIATED**

**DONT FORGET TO MAKE AN UPVOTE, IF YOU LIKED MY WORK**

<img src = "https://i.imgflip.com/19aadg.jpg">

**PEACE OUT $:)$**